
print ("enter your last name")
lastname = input()
print ("enter your last name")
firstname = input()
print ("enter your age")
age = int(input())
print("whats ur height")
height = float(input())
print ("hello, " + lastname + " " + firstname + ":3")   
print  (f"hello, {lastname} {firstname} ! your age is {age} and your height is {height}:3")

print (type(lastname))
print (type(age))
print (age + 2)
print (height + 0.2)